### ISSUE TITLE
git-source-track depends on core.abbrev=7

### ISSUE THREAD

**Issue by auscompgeek** [virtuald/git-source-track#3]
Currently, git-source-track depends on a constant value for `core.abbrev` between developers. (This typically means that `core.abbrev` has to be exactly 7.)

This leads to git-source-track claiming that _every_ file is out of sync when a user sets `core.abbrev` to 12 (for example) in their git config.

**Comment by virtuald** [comment]
Ha, nice, didn't realize it was a setting. I guess one could set this per repository using .gitattributes? Or perhaps it could force it to something, or do prefix matching instead...

**Comment by auscompgeek** [comment]
Luckily repo git configs override user configs (which in turn override system-wide configs), so the workaround is simple enough. It's arguably not a good solution though.

Getting the full commit hashes from the upstream repo and checking the prefix would probably be a nice solution to this.

**Comment by virtuald** [comment]
I'm not actually able to duplicate this bug, it seems to work fine when I set `core.abbrev` to 12. Can you give a specific example?

**Comment by virtuald** [comment]
Also note that with robotpy-wpilib, just about every file IS old. However, pynetworktables is mostly up to date with ntcore.

**Comment by virtuald** [comment]
Oh, I found it. It's when the value in the file is invalid.

**Comment by virtuald** [comment]
Fixed, let me know if that works for you. If so, I'll push it out to pypi.

**Comment by auscompgeek** [comment]
Looks good, thanks!

**Comment by james-ward** [comment]
I don't think the latest version is on pypi, and it currently breaks with the .gittrack config file in robotpy-wpilib.

**Comment by virtuald** [comment]
It'll be there in 5 minutes, sorry about that.

**Comment by virtuald** [comment]
Uploaded.

**Comment by james-ward** [comment]
Thanks, confirmed working. Now to get to work... ;)

**Comment by virtuald** [comment]
Awesome, I'm almost done with fixing up HAL...
